### ISSUE TITLE
Footnotes return link showing garbage character in Safari

### ISSUE THREAD

**Issue by darrylabbate** [rootbeersoup/site#14]
When replacing the default footnote via `sed`, there's a garbage character being inserted to the right of it. At least in Safari. I'm sure it has something to do with the updated Pandoc since the behavior was changed to circumvent something with iOS.

**Comment by darrylabbate** [comment]
Relevant issue: jgm/pandoc#5469

**Comment by darrylabbate** [comment]
<img width="733" alt="Screen Shot 2019-06-28 at 6 37 56 PM" src="https://user-images.githubusercontent.com/9372901/60376334-dc056100-99d3-11e9-8eb2-cb243f1dc906.png">

**Comment by darrylabbate** [comment]
Should be noted that removing the `sed` commands and using the default footnote character doesn't produce the garbage. The garbage also does not appear in the compiled HTML, so it must be a Safari rendering issue.

**Comment by rootbeersoup** [comment]
Ok for some reason it renders perfectly fine on the site itself

<img width="704" alt="Screen Shot 2019-06-28 at 9 18 13 PM" src="https://user-images.githubusercontent.com/9372901/60378605-504aff00-99ea-11e9-9275-005bb7c38902.png">

**Comment by darrylabbate** [comment]
Turns out Pandoc was appending an extra unicode character (`\uFE0E`) to circumvent to emojification on iOS. All that was needed is to print the unicode characters via `perl -CS` and throw that into the `sed` command. I added a [Make variable](https://github.com/rootbeersoup/site/blob/9805b5c11f05c7f66736f8a164ddef0acb7420ae/makefile#L32) to quickly edit this in the future.
